name: CI
on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "**/*.md"

# Publish using custom workflow
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Set up Java'
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'

      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: SDK format check
        run: dart format --set-exit-if-changed ./

      - name: Install dependencies
        working-directory: ./example
        run: flutter pub get

      - name: Test
        run: flutter test

      - name: Build iOS
        working-directory: ./example
        run: flutter build ios --simulator --no-codesign

      - name: Build macOS
        working-directory: ./example
        run: flutter build macos

      - name: Build Android
        working-directory: ./example
        run: flutter build apk

      - name: Build Web
        working-directory: ./example
        run: flutter build web
