name: CI
on:
  push:
    branches:
      - main
      - chore/major-sdks-v3
  pull_request:
    paths-ignore:
      - "**/*.md"

# Publish using custom workflow
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Set up Java'
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'

      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - run: flutter --version

      - name: SDK format check
        working-directory: ./lib
        run: dart format --set-exit-if-changed ./

      - name: Install dependencies
        working-directory: ./example
        run: flutter pub get

      # - name: SDK analyze check
      #   working-directory: ./lib
      #   run: flutter analyze

      - name: Build iOS
        working-directory: ./example
        run: flutter build ios --simulator --no-codesign
      - name: Build Android
        working-directory: ./example
        run: flutter build apk
